<?php
/* This is a system generated file. Please do not modified it manually */
define('SETTING_DELETE_SUC_EN','Message key with all its entries deleted successfully.');
define('SETTING_CONFIRM_DEL_EN','Are you sure to delete this key and all its entries.');
define('SETTING_DUP_KEY_EN','This message key is already exist.');
define('USER_CHK_SESSION_EN','Please login to access this site.');
define('COM_NO_SESSION_EN','You have no more session.Please login again.');
define('COM_DEL_SUCC_EN','Successfully deleted.');
define('COM_DEL_FAIL_EN','Deletion failed.');
define('COM_INS_SUCC_EN','Successfully inserted.');
define('COM_INS_FAIL_EN','Insertion failed.');
define('COM_UPD_SUCC_EN','Successfully updated.');
define('COM_UPD_FAIL_EN','Updation failed.');
define('FILE_INS_SUCC_EN','File stored successfully.');
define('FILE_INS_FAIL_EN','Sorry your file does not stored. Please try once again.');
define('CAT_UPD_SUCC_EN','Category updated successfuly.');
define('CAT_UPD_FAIL_EN','Failed to update category.');
define('CAT_INS_SUCC_EN','Category stored successfully.');
define('CAT_INS_FAIL_EN','Failed to store category.please try again.');
define('EMP_ADD_SUCC_EN','Employee Added Successfully.');
define('EMP_ADD_FAIL_EN','Failed to add employee.');
define('EMP_REC_DEL_SUC_EN','Employees records deleted successfully.');
define('EMP_REC_DEL_FAIL_EN','Failed to delete employee record.');
define('EMP_REMOVE_SUCC_EN','Successfully removed.');
define('EMP_REMOVE_FAIL_EN','Failed in removing.');
define('EMP_SAVE_SUCC_EN','Saved Successfully.');
define('EMP_SAVE_FAIL_EN','Failed to save.');
define('EMP_ASSIGN_SUCC_EN','Assigned Sucessfully.');
define('EMP_ASSIGN_FAIL_EN','Failed in assigning.');
define('EMP_LEAVE_APPLY_SUCC_EN','Applied Sucessfully.');
define('EMP_LEAVE_APPLY_FAIL_EN','Failed in Applying.');
define('EMP_LEAVE_DEL_SUCC_EN','Leave request deleted successfully.');
define('EMP_LEAVE_DEL_FAIL_EN','Failure in deletion.');
define('EMP_TRAVEL_APPLY_SUCC_EN','Applied Sucessfully.');
define('EMP_TRAVEL_APPLY_FAIL_EN','Failed in Applying.');
define('EMP_TRAVEL_DEL_SUCC_EN','Travel request deleted successfully.');
define('EMP_TRAVEL_DEL_FAIL_EN','Failure in deletion.');
define('EMP_PASSWORD_MISMATCH_EN','Your new password and confirm password miss matched.');
define('EMP_PASSWORD_UPD_SUCC_EN','Password updated successfully.');
define('EMP_PASSWORD_UPD_FAIL_EN','Failure in updation.');
define('EMP_ENTER_CORRECT_PWD_EN','Please enter correct old password.');
define('USER_LOGIN_EN','Please enter  Username  &  Password.');
define('USER_MAIL_CONF_EN','Please confirm your email to access this site.');
define('USER_PASS_CONF_EN','Please enter the correct password.');
define('USER_UNAME_EN','Please enter your Username.');
define('USER_ACCOUNT_EN','No such account exists. Contact admin.');
define('USER_FORGOT_PASS_EN','Your password has been sent to your mail id.');
define('USER_RESET_PASS_EN','Your password reset successfully.');
define('USER_LOGIN_FAIL_EN','Please enter correct username and password.');
define('USER_LOGIN_CONF_EN','Your account have already confirmed.You can log in now.');
define('USER_LOGIN_CONF_FAIL_EN','On this current browser one of user is login so you can\'t confirm.');
define('USER_LOGOUT_EN','You have successfully logged out!');
define('EMP_EXPENSE_APPLY_SUCC_EN','Applied Sucessfully.');
define('EMP_EXPENSE_APPLY_FAIL_EN','Failed in Applying.');
define('EMP_EXPENSE_DEL_SUCC_EN','Expense request deleted successfully.');
define('EMP_EXPENSE_DEL_FAIL_EN','Failure in deletion.');
?>
