<?php /* Smarty version 2.6.7, created on 2017-08-24 10:53:23
         compiled from employee/employeeSearch.tpl.html */

$this->_cache_serials['/home/mufeed/html/generatedata/simplehrm/flexycms/../var/localhost/templates_c/default/%%28^289^28920114%%employeeSearch.tpl.html.inc'] = 'a0456d1545288836d82dba53025efda5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'employee/employeeSearch.tpl.html', 24, false),)), $this); ?>
<?php
function _smarty_tplfunc_a0456d1545288836d82dba53025efda5_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'employee','mgr' => 'employee','choice' => 'latestAddModifyViewEmp','flag' => 'view'), $_smarty);
}



?>
