<?php /* Smarty version 2.6.7, created on 2017-08-24 10:54:46
         compiled from adminstration/home.tpl.html */

$this->_cache_serials['/home/mufeed/html/generatedata/simplehrm/flexycms/../var/localhost/templates_c/default/^%%05^05E^05E9657B%%home.tpl.html.inc'] = 'd0acbd86ef707e1ecf0f5af52d27cdce';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'adminstration/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d0acbd86ef707e1ecf0f5af52d27cdce_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'adminstration','mgr' => 'adminstration'), $_smarty);
}



?>
