<?php /* Smarty version 2.6.7, created on 2017-08-24 10:54:46
         compiled from setting/home.tpl.html */

$this->_cache_serials['/home/mufeed/html/generatedata/simplehrm/flexycms/../var/localhost/templates_c/default/^%%18^186^18635D91%%home.tpl.html.inc'] = '1f842954561a2730ba0c9d6bb9f231f8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'setting/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1f842954561a2730ba0c9d6bb9f231f8_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'setting','mgr' => 'setting'), $_smarty);
}



?>
