<?php /* Smarty version 2.6.7, created on 2017-08-24 10:54:08
         compiled from employee/home.tpl.html */

$this->_cache_serials['/home/mufeed/html/generatedata/simplehrm/flexycms/../var/localhost/templates_c/default/^%%87^87E^87EA00F0%%home.tpl.html.inc'] = '738bbfb0050368164242c1cf98c28f03';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'employee/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_738bbfb0050368164242c1cf98c28f03_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'employee','mgr' => 'employee'), $_smarty);
}



?>
