<?php /* Smarty version 2.6.7, created on 2017-08-24 10:48:52
         compiled from tasks/home.tpl.html */

$this->_cache_serials['/home/mufeed/html/generatedata/simplehrm/flexycms/../var/localhost/templates_c/default/^%%8F^8F5^8F51D5B0%%home.tpl.html.inc'] = '8303bde8f1b5177ba3f7aeab87eadbeb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'tasks/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8303bde8f1b5177ba3f7aeab87eadbeb_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'tasks','mgr' => 'tasks'), $_smarty);
}



?>
